### ISSUE TITLE
Manual install wrong parasail binary

### ISSUE THREAD

**Issue by Psy-Fer** [nanoporetech/qcat#5]
Hello,

While installing qcat on our CentOS cluster, I ran into a few snags.
Using conda and pip can be tricky sometimes with these things and user permissions, so gave compling from source a crack.

Using a python 3.6.3 as an example

```
source ~/work/venv363/bin/activate
git clone https://github.com/nanoporetech/qcat.git

pip freeze

numexpr==2.6.5
numpy==1.14.3
pandas==0.23.0
python-dateutil==2.7.3
pytz==2018.4
scipy==1.1.0
six==1.11.0
tables==3.4.3

python3 setup.py install
```
I get the following error, truncated to give the juicy bits.

```
Installed /home/jamfer/work/venv363/lib/python3.6/site-packages/qcat-1.0.1-py3.6.egg
Processing dependencies for qcat==1.0.1
Searching for pyyaml
Reading https://pypi.python.org/simple/pyyaml/
Downloading https://files.pythonhosted.org/packages/a8/c6/a8d1555e795dbd0375c3c93b576ca13bbf139db51ea604afa19a2c35fc03/PyYAML-4.2b4.tar.gz#sha256=3c17fb92c8ba2f525e4b5f7941d850e7a48c3a59b32d331e2502a3cdc6648e76
Best match: PyYAML 4.2b4
Processing PyYAML-4.2b4.tar.gz
Writing /tmp/easy_install-vt1ehea5/PyYAML-4.2b4/setup.cfg
Running PyYAML-4.2b4/setup.py -q bdist_egg --dist-dir /tmp/easy_install-vt1ehea5/PyYAML-4.2b4/egg-dist-tmp-jk207fer
In file included from ext/_yaml.c:565:0:
ext/_yaml.h:2:18: fatal error: yaml.h: No such file or directory
compilation terminated.
Error compiling module, falling back to pure Python
zip_safe flag not set; analyzing archive contents...
Moving PyYAML-4.2b4-py3.6-linux-x86_64.egg to /home/jamfer/work/venv363/lib/python3.6/site-packages
Adding PyYAML 4.2b4 to easy-install.pth file
```

and 

```
Installed /home/jamfer/work/venv363/lib/python3.6/site-packages/PyYAML-4.2b4-py3.6-linux-x86_64.egg
Searching for parasail
Reading https://pypi.python.org/simple/parasail/
Downloading https://files.pythonhosted.org/packages/26/68/2e051763c912e9814c5bd8f4b0b9ca3e846cf62c44a3b250852298454482/parasail-1.1.16.tar.gz#sha256=00d2be6b78368667376a7a0eae265a1a9c35ed210a546902340f621f32f28078
Best match: parasail 1.1.16
Processing parasail-1.1.16.tar.gz
Writing /tmp/easy_install-ihokcr4y/parasail-1.1.16/setup.cfg
Running parasail-1.1.16/setup.py -q bdist_egg --dist-dir /tmp/easy_install-ihokcr4y/parasail-1.1.16/egg-dist-tmp-rqpuzx7r
Traceback (most recent call last):
  File "/home/jamfer/work/venv363/lib/python3.6/site-packages/setuptools/sandbox.py", line 157, in save_modules
    yield saved
  File "/home/jamfer/work/venv363/lib/python3.6/site-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/home/jamfer/work/venv363/lib/python3.6/site-packages/setuptools/sandbox.py", line 248, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/home/jamfer/work/venv363/lib/python3.6/site-packages/setuptools/sandbox.py", line 278, in run
    return func()
  File "/home/jamfer/work/venv363/lib/python3.6/site-packages/setuptools/sandbox.py", line 246, in runner
    _execfile(setup_script, ns)
  File "/home/jamfer/work/venv363/lib/python3.6/site-packages/setuptools/sandbox.py", line 47, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-ihokcr4y/parasail-1.1.16/setup.py", line 18, in <module>
    install_requires=[
ModuleNotFoundError: No module named 'wheel'
```

So, the end result of that is:

```
ModuleNotFoundError: No module named 'wheel'
```

so, I do a 
```
pip install wheel
```

```
Collecting wheel
  Downloading https://files.pythonhosted.org/packages/96/ba/a4702cbb6a3a485239fbe9525443446203f00771af9ac000fa3ef2788201/wheel-0.33.1-py2.py3-none-any.whl
qcat 1.0.1 requires biopython, which is not installed.
qcat 1.0.1 requires parasail, which is not installed.
Installing collected packages: wheel
Successfully installed wheel-0.33.1
````

I run the install again
```
python3 setup.py install
````
That works fun, other than a bunch of warnings from biopython.

I then do a 
````
qcat -h
```
and I get the following error, in full:
````
Traceback (most recent call last):
  File "/home/jamfer/work/venv363/bin/qcat", line 11, in <module>
    load_entry_point('qcat==1.0.1', 'console_scripts', 'qcat')()
  File "/home/jamfer/work/venv363/lib/python3.6/site-packages/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/jamfer/work/venv363/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/home/jamfer/work/venv363/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/home/jamfer/work/venv363/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/home/jamfer/work/venv363/lib/python3.6/site-packages/qcat-1.0.1-py3.6.egg/qcat/cli.py", line 14, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/home/jamfer/work/venv363/lib/python3.6/site-packages/qcat-1.0.1-py3.6.egg/qcat/config.py", line 5, in <module>
  File "/home/jamfer/work/venv363/lib/python3.6/site-packages/parasail-1.1.16-py3.6.egg/parasail/__init__.py", line 30, in <module>
    _lib = ctypes.CDLL(_libname)
  File "/home/jamfer/work/python363/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libparasail.so: cannot open shared object file: No such file or directory
````
so, it is looking for the `libparasail.so` file.
If we look in the parasail folder in site-packages, there is no  `libparasail.so` to be found.

So, I try the obvous:
```
pip install parasail
```
but that doesn't do anything and just confirms it's installed. But it still fails to find that data.

So I go look at parasail github, and I clone that.
I follow the instructions for compiling like so
```
python setup.py bdist_wheel
```
This takes a while, but gives me `/home/jamfer/work/parasail-python/parasail-master/.libs/libparasail.so.3.6.3`

I then link that into `/home/jamfer/work/venv363/lib/python3.6/site-packages/parasail-1.1.16-py3.6.egg/parasail`
```
ln -s /home/jamfer/work/parasail-python/parasail-master/.libs/libparasail.so.3.6.3 libparasail.so
```

Give `qcat -h` a crack, and now it works.

Unfortunately, we are getting only around 50% recovery from our 96 barcode kit, though it might be an issue with the kit rather than qcat. 

Anyway, seems when parasail is being compiled during the qcat install, it's not creating the .so file, even though I can see it specifically runs the bdist_wheel command for it. weird.

Hope this helps.

James F.

**Comment by Psy-Fer** [comment]
oh, when I did this for python 3.4.0, I got a parasail.dll file (for windows) instead of a .so file. 
I re-did it on 3.6.3, to grab the errors.

**Comment by liny601** [comment]
Hello James,

Thank you so much for sharing your experience.

However, we tried to link the libparasail as per your instruction. We are not sure where to link the .so file to.

When we run qcat, the following error popped up.

`nanopore@Nanopore-Server:~/qcat$ qcat -h
Traceback (most recent call last):
  File "/usr/local/bin/qcat", line 11, in <module>
    load_entry_point('qcat==1.0.3', 'console_scripts', 'qcat')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "build/bdist.linux-x86_64/egg/qcat/cli.py", line 14, in <module>
  File "build/bdist.linux-x86_64/egg/qcat/config.py", line 5, in <module>
  File "/home/nanopore/.local/lib/python2.7/site-packages/parasail/__init__.py", line 29, in <module>
    _lib = ctypes.CDLL(_libname)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libparasail.so: cannot open shared object file: No such file or directory`

Any input in much appreciated.

Regards
Linh

**Comment by Psy-Fer** [comment]
hello,

So I manually install parasail
then in that folder, I find something along the lines of:
`<installpath>/parasail-python/parasail-master/.libs/libparasail.so.3.6.3`
I then link that in my virtual environment's parasail install somewhere like here:
`<virtualenv>/lib/python3.6/site-packages/parasail-1.1.16-py3.6.egg/parasail`

It will depend on your install path.

also, I think qcat was made to run on python 3, not 2. So i'd use that instead as well.

**Comment by TimD1** [comment]
For me what worked was `pip install wheel parasail==1.1.16`. I ran into the same issues as you with parasail 1.2.

**Comment by iiSeymour** [comment]
@TimD1  I added prebuilt multi-platform wheels in `parasail=1.1.20`. This should make things much simpler as you don't need to compile the wheel client side. What issues did you run in to?

**Comment by TimD1** [comment]
@iiSeymour I first cloned the newest stable version of qcat:
`$ git clone https://github.com/nanoporetech/qcat --branch v1.1.0`
Then I created a virtual environment for building and running qcat:
`$ python3 -m venv venv3
$ source venv3/bin/activate
$ pip install --upgrade pip`
Then I ran the installation script as suggested in the repo's README:
`$ python setup.py install`
I got errors for wheel and Cython:
`ImportError: No module named 'wheel'`
`RuntimeError: Running cythonize failed!`
I fixed this by installing them:
`$ pip install wheel cython`
After this, qcat successfully built but fails to run:
`$ qcat -h
Traceback (most recent call last):
  File "/home/timdunn/software/qcat2/venv3/bin/qcat", line 9, in <module>
    load_entry_point('qcat==1.1.0', 'console_scripts', 'qcat')()
  File "/home/timdunn/software/qcat2/venv3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/timdunn/software/qcat2/venv3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/home/timdunn/software/qcat2/venv3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/home/timdunn/software/qcat2/venv3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/home/timdunn/software/qcat2/venv3/lib/python3.5/site-packages/qcat-1.1.0-py3.5.egg/qcat/cli.py", line 14, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/home/timdunn/software/qcat2/venv3/lib/python3.5/site-packages/qcat-1.1.0-py3.5.egg/qcat/config.py", line 5, in <module>
  File "/home/timdunn/software/qcat2/venv3/lib/python3.5/site-packages/parasail-1.2-py3.5.egg/parasail/__init__.py", line 70, in <module>
    raise Exception("failed to locate and open '{}'".format(_libname))
Exception: failed to locate and open 'libparasail.so'
I saw that PsyFer's installation worked with parasail 1.1.16, so I replaced the existing installation of parasail with that version and everything worked (no need to re-run setup.py):
`$ pip install parasail=1.1.16`
Hope this helps
