### ISSUE TITLE
Failed to install on Ubuntu using python3.5

### ISSUE THREAD

**Issue by liny601** [nanoporetech/qcat#9]
Hello,

I had a few hiccups when trying to install qcat in Ubuntu 16. Each time running the command, I had the following errors:

`nanopore@MinION:~/qcat$ qcat -h
Traceback (most recent call last):
  File "/usr/local/bin/qcat", line 9, in <module>
    load_entry_point('qcat==1.0.3', 'console_scripts', 'qcat')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/usr/local/lib/python3.5/dist-packages/qcat-1.0.3-py3.5.egg/qcat/cli.py", line 14, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/usr/local/lib/python3.5/dist-packages/qcat-1.0.3-py3.5.egg/qcat/config.py", line 5, in <module>
  File "/usr/local/lib/python3.5/dist-packages/parasail-1.1.16-py3.5.egg/parasail/__init__.py", line 30, in <module>
    _lib = ctypes.CDLL(_libname)
  File "/usr/lib/python3.5/ctypes/__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libparasail.so: cannot open shared object file: No such file or directory`

We already to install parasail manually & link the libparasail.so into this directory:
`/usr/local/lib/python3.5/dist-packages/parasail-1.1.16-py3.5.egg/parasail/`

Any input is much appreciated.

Regards
Linh

**Comment by philres** [comment]
Hi Linh,

thanks for reporting. It looks like a problem with installing one of the libraries (parasail) qcat is using. Could you tell me the exact steps you did for installing qcat, your exact version of Ubuntu and python?

In the mean time installing qcat using miniconda/bioconda would fix this problem.

Thanks,
Philipp
